export const quiz5 = {
  quizTitle: 'Za co Cię kocham',
  quizSynopsis: '',
  nrOfQuestions: '10',
  progressBarColor: '#9de1f6',
  questions: [
    {
      question: 'Za to jak się o mnie troszczysz:',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Gdy robisz mi herbatkę jak jestem chory',
        'Jak robisz mi jedzonko jak późno wracam',
        'Przykrywasz mnie kocykiem jak robię drzemkę',
        'Smarujesz mi pysia sunstickiem',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Za to że jesteś odważna:',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Gdy podejmujesz nowe wyzwania w pracy',
        'Jak przezwyciężasz strach na ściance',
        'Jak próbujesz wciąż nowych rzeczy',
        'Że walczysz o to co uważasz za słuszne',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Że jesteś śmieszkiem',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Jak mówisz "Skup się Moniczko"',
        'Jak mnie rozśmieszasz kiedy jestem zły',
        'Jak sobie czasem tak trochę tańczysz bez powodu',
        'Jak rozmawiasz z jedzonkiem',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Że się starasz',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Że nawet jak mamy ciężki czas to walczysz o nasz związek',
        'Że nie chowasz urazy',
        'Za to że mnie słuchasz',
        'Że dbasz o nasze relacje z innymi',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Za te wszystkie lata razem',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Że dalej nam się chce',
        'Że czujemy się dobrze w swoim towarzystwie',
        'Że mamy tyle wspólnego',
        'Za drogę którą przeszliśmy',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Że jesteś najlepszą partnerką podróży:',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Że jak się coś wysypie to nie masz z tym problemu',
        'Że odnajdujesz się w tuktuku i pięciogwiazdkowym hotelu',
        'Że chcesz smakować, potraw i życia',
        'Że każde odzwiedzane z Tobą miejsce jest super',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Za to jaka jesteś dla innych',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Że oczarowujesz wszystkie dzieci',
        'I umiesz się z każdym dogadać',
        'Że jesteś zawsze gotowa pomagać przyjaciołom',
        'Że dbasz o nasze rodziny',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Za to kim jesteś',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Że nie udajesz',
        'Że cieszysz się z tego co masz',
        'Że jesteś rozsądna',
        'Że jesteś moim misiakiem :*',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Za Twój zmysł estetyczny',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Za urządzanie nam domków',
        'Za pomaganie wszyskim z dizajnami',
        'Za dobre oko do ciuchów',
        'No i dobre oko do mężczyzn',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
    {
      question: 'Za wszystko inne',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Że się do mnie przytulasz jak śpisz',
        'Że czasem jesteś charpaganem' ,
        'Że czasem jesteś ziemniaczkiem',
        'Że jak masz czipsy to się nimi dzielisz',
      ],
      correctAnswer: [1, 2, 3, 4],
      messageForCorrectAnswer: '<3',
      messageForIncorrectAnswer: '',
      explanation: '',
      point: '10',
    },
  ],
};